language: python
python:
  - "3.7.3"

# command to install dependencies
install:
  - pip install -r requirements.txt

stages:
  - name: interpretacao
jobs:
  include:
    - stage: interpretacao
      name: Deploy para o Heroku
      script: /bin/true
      interpretacao:
        provider: heroku
        app: projeto-autros
        on: master
        run: "python manage.py migrate"
