# Generated by Django 2.2.4 on 2020-06-28 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dispositivo_de_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('status', models.BooleanField(verbose_name=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modulo', to='api.dispositivo_de_saida')),
            ],
        ),
        migrations.DeleteModel(
            name='modulos',
        ),
    ]
